version: '3.1'

services:

  php:
    build: docker/php
    container_name: foodApi
    #image: dunglas/frankenphp
    # uncomment the following line if you want to use a custom Dockerfile
    #build: .
    # uncomment the following line if you want to run this in a production environment
    # restart: always
    #stdin_open: true
    #tty: true
    environment:
      APP_NAME: FOOD_API
    ports:
      - "6110:80"
      - "6111:443"
    volumes:
      - ./app:/app
    links:
      - database
    extra_hosts:
      - host.docker.internal:host-gateway

  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: ChangeMe!
      POSTGRES_USER: app
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: